on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake pkg-config check libsubunit-dev cppcheck doxygen libsystemd-dev libcurl4-gnutls-dev libmicrohttpd-dev libjansson-dev
        wget https://github.com/benmcollins/libjwt/archive/v1.10.2.tar.gz -O libjwt-1.10.2.tar.gz
        tar xzf libjwt-1.10.2.tar.gz
        pushd libjwt-1.10.2 && autoreconf -i && ./configure && make && sudo make install && popd
        rm -rf libjwt-1.10.2
        sudo ldconfig
    - name: cppcheck
      run: cppcheck --force --enable=warning,missingInclude --error-exitcode=1 .
    - name: build
      run: |
        cd test
        make test
        cd ..
        mkdir build
        cd build
        cmake -DBUILD_IDDAWC_TESTING=on ..
        make test package
        sudo make install
        sudo ldconfig
